---
- include: import-nginxconf.yml
- include: import-ssl.yml
- include: storage-fixpermissions.yml
- include: composer-install.yml
- include: import-dotenv.yml

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted